on: push
name: Really cool Reactor demo
jobs:
  build-job:
    name: Build .Net Project
    runs-on : ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - run: dotnet --version
        name: Check .Net Version
